
CREATE TABLE offermanager.Organization (
    OrganizationId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Organization PRIMARY KEY CLUSTERED
        DEFAULT NEWSEQUENTIALID(),
    Name NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Organization_CreatedAt DEFAULT SYSUTCDATETIME()
);
