
CREATE TABLE offermanager.Organization (
    OrganizationId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Organization PRIMARY KEY CLUSTERED,
    Name NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Organization_CreatedAt DEFAULT SYSUTCDATETIME()
);
